language: php
php:
  - 7.1.9
  - 7.0
  - nightly
  - hhvm
before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

cache:
  directories:
    - node_modules
    - vendor

after_success:
  - bash <(curl -s https://codecov.io/bash)