language: php
php:
  - 7.0.21
  - 7.1
  - 7.2
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

cache:
  directories:
    - node_modules
    - vendor

after_success:
  - bash <(curl -s https://codecov.io/bash)